[tool.poetry]
name = "gem-poacher"
version = "0.3.0"
description = ""
authors = ["hojahoja"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pygame = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
